version: '3'

services:

  web:
    restart: "always"
    container_name: punzh_django
    volumes:
      - ./app:/app
    build:
      context: ./
      dockerfile: images/django/Dockerfile
    depends_on:
      - db
    command: python manage.py runserver --insecure 0.0.0.0:8000
    ports:
      - 80:8000
    networks:
      - punzh-net

  db:
    container_name: punzh_db
    image: postgres:14
    restart: "always"
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=punzh_dict
    networks:
        - punzh-net

networks:
  punzh-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.110.0/28
