# Generated by Django 3.1.7 on 2021-04-07 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=255, unique=True)),
                ('first_letter', models.CharField(db_index=True, max_length=1)),
                ('first_trigram', models.CharField(max_length=3)),
                ('article_html', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dict.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSearchIndex',
            fields=[
                ('word', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.article')),
            ],
        ),
    ]
