# Generated by Django 3.1.7 on 2022-04-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название источника')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('css', models.CharField(blank=True, max_length=255, null=True, verbose_name='CSS Styling')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Слово (ориг.)')),
                ('word_normalized', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='Коррекция заголовка')),
                ('first_letter', models.CharField(db_index=True, max_length=1)),
                ('first_trigram', models.CharField(max_length=3)),
                ('article_html', models.TextField(default='', verbose_name='Словарная статья (html)')),
                ('source_detalization', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Уточнение источника')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleIndexWordNormalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.article')),
            ],
            options={
                'unique_together': {('word', 'article')},
            },
        ),
        migrations.CreateModel(
            name='ArticleIndexWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.article')),
            ],
            options={
                'unique_together': {('word', 'article')},
            },
        ),
        migrations.CreateModel(
            name='ArticleIndexTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus_word', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Перевод')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.article')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
                'ordering': ['rus_word'],
                'unique_together': {('rus_word', 'article')},
            },
        ),
    ]
