# Generated by Django 3.1.7 on 2021-03-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('word_slug', models.CharField(max_length=255)),
                ('first_letter', models.CharField(max_length=1)),
                ('first_trigram', models.CharField(max_length=3)),
                ('definition', models.TextField()),
            ],
        ),
    ]
