# Generated by Django 3.1.7 on 2022-04-25 15:46

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]