# Generated by Django 3.1.7 on 2021-03-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='definition',
            field=models.TextField(default=''),
        ),
    ]
