# Generated by Django 3.1.7 on 2022-04-25 15:49

from django.db import migrations


def create_third_party_extension(apps, schema_editor):
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;")


def drop_third_party_extension(apps, schema_editor):
    schema_editor.execute("DROP EXTENSION IF EXISTS fuzzystrmatch;")


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_auto_20220425_1546'),
    ]

    operations = [
        migrations.RunPython(create_third_party_extension, reverse_code=drop_third_party_extension, atomic=True)
    ]