# Generated by Django 3.1.7 on 2021-03-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_auto_20210327_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='definition',
        ),
    ]
