# Generated by Django 3.1.7 on 2022-10-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_auto_20220425_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='linked_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict.article', verbose_name='см.'),
        ),
    ]
