# Generated by Django 3.1.7 on 2021-11-14 14:09

from django.db import migrations


def change_first_letter(apps, schema_editor):

    Article = apps.get_model('dict', 'Article')
    for article in Article.objects.all().filter(first_letter='Ü'):
        article.first_letter = 'Y'
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0006_auto_20211017_1143'),
    ]

    operations = [
           migrations.RunPython(change_first_letter),
    ]
