# Generated by Django 3.1.7 on 2022-01-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0009_auto_20220118_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict.source', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='source',
            name='css',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
