# Generated by Django 3.1.7 on 2022-01-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0010_auto_20220118_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='source_id',
            new_name='source',
        ),
    ]
