# Generated by Django 3.1.7 on 2023-08-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0011_auto_20221106_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_html', models.TextField(default='', verbose_name='Словарная статья (html)')),
                ('source_detalization', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Уточнение источника')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.article')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Дополнение к словарной статье',
                'verbose_name_plural': 'Дополнения',
                'ordering': ['id'],
            },
        ),
    ]
