# Generated by Django 3.1.7 on 2022-02-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0011_auto_20220118_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['id'], 'verbose_name': 'Источник', 'verbose_name_plural': 'Источники'},
        ),
        migrations.AlterField(
            model_name='source',
            name='css',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CSS Styling'),
        ),
    ]
