# Generated by Django 3.1.7 on 2022-02-19 15:00

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0012_auto_20220218_1721'),
    ]

    operations = [
        TrigramExtension()
    ]
