# Generated by Django 3.1.7 on 2025-02-14 16:33

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0012_articleaddition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleaddition',
            options={'ordering': ['-id'], 'verbose_name': 'Аддендум', 'verbose_name_plural': 'Дополнение к словарной статье'},
        ),
        migrations.AddField(
            model_name='articleindextranslate',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articleaddition',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='dict.article'),
        ),
    ]
