# Generated by Django 3.1.7 on 2022-02-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0014_auto_20220219_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndexWordNormalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.article')),
            ],
            options={
                'unique_together': {('word', 'article')},
            },
        ),
    ]
