# Generated by Django 3.1.7 on 2026-08-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dict", "0017_auto_20260803_1021"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["id"],
                "verbose_name": "Помета",
                "verbose_name_plural": "Пометы",
            },
        ),
        migrations.AlterField(
            model_name="articleindextag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dict.tag",
                verbose_name="Помета",
            ),
        ),
    ]
