# Generated by Django 3.1.7 on 2026-08-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0018_auto_20260803_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Смысловое поле')),
                ('definition', models.TextField(blank=True, default='', verbose_name='Определение')),
                ('sorting', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Сортировка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dict.semanticfield', verbose_name='Родительское поле')),
            ],
            options={
                'verbose_name': 'Смысловое поле',
                'verbose_name_plural': 'Смысловые поля',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSemanticField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.article')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.semanticfield', verbose_name='Смысловое поле')),
            ],
            options={
                'verbose_name': 'Смысловое поле статьи',
                'verbose_name_plural': 'Смысловые поля статей',
                'unique_together': {('article', 'field')},
            },
        ),
    ]
