# Generated by Django 3.1.7 on 2026-08-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0020_articlekeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.IntegerField(choices=[(1, 'Населенные пункты'), (2, 'Часть речи'), (3, 'Стилистические пометы'), (4, 'Говоры'), (5, 'Фразеологизмы')]),
        ),
    ]
