# Generated by Django 3.1.7 on 2026-08-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dict", "0021_auto_20260804_1037"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="first_trigram",
        ),
    ]
