# Generated by Django 3.1.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dict", "0022_remove_article_first_trigram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlesemanticfield",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semantic_assignments",
                to="dict.article",
            ),
        ),
        migrations.AlterField(
            model_name="articlesemanticfield",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="dict.semanticfield",
                verbose_name="Смысловое поле",
            ),
        ),
    ]
