# Generated by Django 3.1.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dict", "0023_articlesemanticfield_related_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesemanticfield",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Главное"),
        ),
        migrations.AddConstraint(
            model_name="articlesemanticfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_primary=True),
                fields=("article",),
                name="dict_asf_one_primary_per_article",
            ),
        ),
    ]
