# Generated by Django 3.1.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dict", "0024_articlesemanticfield_is_primary"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="articlesemanticfield",
            name="dict_asf_one_primary_per_article",
        ),
        migrations.RenameField(
            model_name="articlesemanticfield",
            old_name="is_primary",
            new_name="from_translation",
        ),
        migrations.AlterField(
            model_name="articlesemanticfield",
            name="from_translation",
            field=models.BooleanField(default=False, verbose_name="По переводу"),
        ),
    ]
