# Generated by Django 3.1.7

from django.db import migrations, models


def backfill_articlelink_kind(apps, schema_editor):
    ArticleLink = apps.get_model("dict", "ArticleLink")
    Article = apps.get_model("dict", "Article")
    from dict.see_audit import infer_link_kind

    by_id = Article.objects.in_bulk()
    batch = []
    for link in ArticleLink.objects.iterator():
        from_art = by_id.get(link.from_article_id)
        to_art = by_id.get(link.to_article_id)
        if not from_art or not to_art:
            continue
        kind = infer_link_kind(from_art, to_art)
        if link.kind != kind:
            link.kind = kind
            batch.append(link)
        if len(batch) >= 500:
            ArticleLink.objects.bulk_update(batch, ["kind"])
            batch = []
    if batch:
        ArticleLink.objects.bulk_update(batch, ["kind"])


class Migration(migrations.Migration):

    dependencies = [
        ("dict", "0025_articlesemanticfield_from_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlelink",
            name="kind",
            field=models.CharField(
                choices=[("see", "см."), ("cf", "ср."), ("deriv", "от")],
                db_index=True,
                default="see",
                max_length=8,
                verbose_name="Тип связи",
            ),
        ),
        migrations.RunPython(backfill_articlelink_kind, migrations.RunPython.noop),
    ]
